"""fix column name

Revision ID: c6d9b9ab6738
Revises: f48a8c61e6f7
Create Date: 2023-09-21 12:08:40.685210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d9b9ab6738'
down_revision: Union[str, None] = 'f48a8c61e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamento', sa.Column('valor', sa.Float(), nullable=True))
    op.drop_column('pagamento', 'cidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamento', sa.Column('cidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pagamento', 'valor')
    # ### end Alembic commands ###
